### ISSUE TITLE
don't require github password?

### ISSUE THREAD

**Issue by warner** [sigma/magit-gh-pulls#5] opened 2013-09-19 21:33 UTC
I started to play with magit-gh-pulls, and think I got it configured ok (running magit-gh-pulls-mode from within a *magit* buffer). But it immediately asks me for my github password. Pull requests are public, and (as far as I can tell) this mode doesn't do anything on github that would require authorization.

Is there an easy way to make this work without giving it read+write account access? Is it a limitation of the underlying gh.el library?

**Comment by alexander-yakushev** [comment] 2015-10-12 10:49
Since we figured out that the problem is in `gh.el`, I'm closing this issue.

Accumulated wisdom from @aspiers: evaluating `(defvar gh-auth-alist nil)` clears gh.el token cache and forces it to reread `~/.gitconfig` file.

**Closed by alexander-yakushev** 2015-10-12 10:49 UTC
