### ISSUE TITLE
fetching PR is broken with last magit

### ISSUE THREAD

**Issue by syl20bnr** [sigma/magit-gh-pulls#60] opened 2015-11-15 15:00 UTC
With latest magit, fetching PRs ends with an empty list of PRs, no error, no backtrace.

**Comment by lunaryorn** [comment] 2015-11-17 19:46
It's caused by `magit-gh-pulls-insert-gh-pulls` using `magit-insert` which is gone in recent Magit apparently.

If you replace `condition-case` with `condition-case-unless-debug` (see #61) and enable `debug-on-error` you get the following backtrace:

```
Debugger entered--Lisp error: (void-function magit-insert)
  (magit-insert heading)
  (catch (quote cancel-section) (message "DEBUG: Insert unfetched pull: %s" (eieio-oref stub (quote :title))) (magit-insert heading) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section145) (set-marker-insertion-type (progn nil (or (and (memq (aref section145 0) cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list (quote magit-section) section145))) (aref section145 3)) t) (let* ((end (progn nil (or (and (memq ... cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list ... section145))) (let* ((v section145)) (aset v 5 (point-marker))))) (map (intern (format "magit-%s-section-map" (progn nil (or ... ...) (aref section145 1))))) (map (and (boundp map) (symbol-value map)))) (save-excursion (goto-char (progn nil (or (and (memq ... cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list ... section145))) (aref section145 3))) (while (< (point) end) (let ((next (or ... end))) (if (get-text-property (point) (quote magit-section)) nil (put-text-property (point) next (quote magit-section) section145) (if map (progn ...))) (goto-char next))))) (if (eq section145 magit-root-section) (magit-section-show section145) (progn nil (or (and (memq (aref (progn nil ... ...) 0) cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list (quote magit-section) (progn nil (or ... ...) (aref section145 12))))) (let* ((v (progn nil (or ... ...) (aref section145 12)))) (aset v 13 (nconc (progn nil (or ... ...) (aref ... 13)) (list section145)))))))
  (let ((magit-insert-section--current section145) (magit-insert-section--parent section145) (magit-insert-section--oldroot (or magit-insert-section--oldroot (if magit-insert-section--parent nil (prog1 magit-root-section (setq magit-root-section section145)))))) (catch (quote cancel-section) (message "DEBUG: Insert unfetched pull: %s" (eieio-oref stub (quote :title))) (magit-insert heading) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section145) (set-marker-insertion-type (progn nil (or (and (memq (aref section145 0) cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list (quote magit-section) section145))) (aref section145 3)) t) (let* ((end (progn nil (or (and ...) (signal ... ...)) (let* (...) (aset v 5 ...)))) (map (intern (format "magit-%s-section-map" (progn nil ... ...)))) (map (and (boundp map) (symbol-value map)))) (save-excursion (goto-char (progn nil (or (and ...) (signal ... ...)) (aref section145 3))) (while (< (point) end) (let ((next ...)) (if (get-text-property ... ...) nil (put-text-property ... next ... section145) (if map ...)) (goto-char next))))) (if (eq section145 magit-root-section) (magit-section-show section145) (progn nil (or (and (memq (aref ... 0) cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list (quote magit-section) (progn nil ... ...)))) (let* ((v (progn nil ... ...))) (aset v 13 (nconc (progn nil ... ...) (list section145))))))) section145)
  (let* ((section145 (progn "Constructor for objects of type `magit-section'." nil (vector (quote cl-struct-magit-section) (quote unfetched-pull) info (point-marker) nil nil nil nil nil nil nil nil magit-insert-section--parent nil)))) (progn nil (or (and (memq (aref section145 0) cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list (quote magit-section) section145))) (let* ((v section145)) (aset v 6 (let ((value (run-hook-with-args-until-success ... section145))) (if value (eq value (quote hide)) (let (...) (if it ... nil))))))) (let ((magit-insert-section--current section145) (magit-insert-section--parent section145) (magit-insert-section--oldroot (or magit-insert-section--oldroot (if magit-insert-section--parent nil (prog1 magit-root-section (setq magit-root-section section145)))))) (catch (quote cancel-section) (message "DEBUG: Insert unfetched pull: %s" (eieio-oref stub (quote :title))) (magit-insert heading) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section145) (set-marker-insertion-type (progn nil (or (and (memq ... cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list ... section145))) (aref section145 3)) t) (let* ((end (progn nil (or ... ...) (let* ... ...))) (map (intern (format "magit-%s-section-map" ...))) (map (and (boundp map) (symbol-value map)))) (save-excursion (goto-char (progn nil (or ... ...) (aref section145 3))) (while (< (point) end) (let (...) (if ... nil ... ...) (goto-char next))))) (if (eq section145 magit-root-section) (magit-section-show section145) (progn nil (or (and (memq ... cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list ... ...))) (let* ((v ...)) (aset v 13 (nconc ... ...)))))) section145))
  (cond (have-commits (let* ((section143 (progn "Constructor for objects of type `magit-section'." nil (vector (quote cl-struct-magit-section) (quote pull) info (point-marker) nil nil nil nil nil nil nil nil magit-insert-section--parent nil)))) (progn nil (or (and (memq (aref section143 0) cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list (quote magit-section) section143))) (let* ((v section143)) (aset v 6 (let (...) (if value ... ...))))) (let ((magit-insert-section--current section143) (magit-insert-section--parent section143) (magit-insert-section--oldroot (or magit-insert-section--oldroot (if magit-insert-section--parent nil ...)))) (catch (quote cancel-section) (magit-insert heading) (magit-insert-heading) (if (and have-commits (not applied)) (progn (magit-git-wash ... "cherry" "-v" ... base-sha head-sha))) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section143) (set-marker-insertion-type (progn nil (or ... ...) (aref section143 3)) t) (let* ((end ...) (map ...) (map ...)) (save-excursion (goto-char ...) (while ... ...))) (if (eq section143 magit-root-section) (magit-section-show section143) (progn nil (or ... ...) (let* ... ...)))) section143))) (invalid (let* ((section144 (progn "Constructor for objects of type `magit-section'." nil (vector (quote cl-struct-magit-section) (quote invalid-pull) info (point-marker) nil nil nil nil nil nil nil nil magit-insert-section--parent nil)))) (progn nil (or (and (memq (aref section144 0) cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list (quote magit-section) section144))) (let* ((v section144)) (aset v 6 (let (...) (if value ... ...))))) (let ((magit-insert-section--current section144) (magit-insert-section--parent section144) (magit-insert-section--oldroot (or magit-insert-section--oldroot (if magit-insert-section--parent nil ...)))) (catch (quote cancel-section) (magit-insert heading) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section144) (set-marker-insertion-type (progn nil (or ... ...) (aref section144 3)) t) (let* ((end ...) (map ...) (map ...)) (save-excursion (goto-char ...) (while ... ...))) (if (eq section144 magit-root-section) (magit-section-show section144) (progn nil (or ... ...) (let* ... ...)))) section144))) (t (let* ((section145 (progn "Constructor for objects of type `magit-section'." nil (vector (quote cl-struct-magit-section) (quote unfetched-pull) info (point-marker) nil nil nil nil nil nil nil nil magit-insert-section--parent nil)))) (progn nil (or (and (memq (aref section145 0) cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list (quote magit-section) section145))) (let* ((v section145)) (aset v 6 (let (...) (if value ... ...))))) (let ((magit-insert-section--current section145) (magit-insert-section--parent section145) (magit-insert-section--oldroot (or magit-insert-section--oldroot (if magit-insert-section--parent nil ...)))) (catch (quote cancel-section) (message "DEBUG: Insert unfetched pull: %s" (eieio-oref stub (quote :title))) (magit-insert heading) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section145) (set-marker-insertion-type (progn nil (or ... ...) (aref section145 3)) t) (let* ((end ...) (map ...) (map ...)) (save-excursion (goto-char ...) (while ... ...))) (if (eq section145 magit-root-section) (magit-section-show section145) (progn nil (or ... ...) (let* ... ...)))) section145))))
  (let* ((id (eieio-oref stub (quote :number))) (req (eieio-oref (gh-pulls-get api user proj id) (quote :data))) (base-sha (eieio-oref (eieio-oref req (quote :base)) (quote :sha))) (base-ref (eieio-oref (eieio-oref req (quote :base)) (quote :ref))) (head-sha (eieio-oref (eieio-oref req (quote :head)) (quote :sha))) (invalid (equal (eieio-oref (eieio-oref req (quote :head)) (quote :ref)) head-sha)) (have-commits (and (eql 0 (magit-git-exit-code "cat-file" "-e" base-sha)) (eql 0 (magit-git-exit-code "cat-file" "-e" head-sha)))) (applied (and have-commits (magit-git-string "branch" branch (format "--contains=%s" head-sha)))) (heading (format "[%s@%s] %s\n" (propertize (number-to-string id) (quote face) (quote magit-tag)) (if (string= base-ref branch) (propertize base-ref (quote face) (quote magit-branch-local)) base-ref) (propertize (eieio-oref req (quote :title)) (quote face) (cond (applied (quote magit-cherry-equivalent)) (have-commits nil) (invalid (quote error)) (t (quote italic)))))) (info (list user proj id))) (message "DEBUG %s: have commits: %S" (eieio-oref stub (quote :title)) have-commits) (cond (have-commits (let* ((section143 (progn "Constructor for objects of type `magit-section'." nil (vector ... ... info ... nil nil nil nil nil nil nil nil magit-insert-section--parent nil)))) (progn nil (or (and (memq ... cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list ... section143))) (let* ((v section143)) (aset v 6 (let ... ...)))) (let ((magit-insert-section--current section143) (magit-insert-section--parent section143) (magit-insert-section--oldroot (or magit-insert-section--oldroot ...))) (catch (quote cancel-section) (magit-insert heading) (magit-insert-heading) (if (and have-commits ...) (progn ...)) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section143) (set-marker-insertion-type (progn nil ... ...) t) (let* (... ... ...) (save-excursion ... ...)) (if (eq section143 magit-root-section) (magit-section-show section143) (progn nil ... ...))) section143))) (invalid (let* ((section144 (progn "Constructor for objects of type `magit-section'." nil (vector ... ... info ... nil nil nil nil nil nil nil nil magit-insert-section--parent nil)))) (progn nil (or (and (memq ... cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list ... section144))) (let* ((v section144)) (aset v 6 (let ... ...)))) (let ((magit-insert-section--current section144) (magit-insert-section--parent section144) (magit-insert-section--oldroot (or magit-insert-section--oldroot ...))) (catch (quote cancel-section) (magit-insert heading) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section144) (set-marker-insertion-type (progn nil ... ...) t) (let* (... ... ...) (save-excursion ... ...)) (if (eq section144 magit-root-section) (magit-section-show section144) (progn nil ... ...))) section144))) (t (let* ((section145 (progn "Constructor for objects of type `magit-section'." nil (vector ... ... info ... nil nil nil nil nil nil nil nil magit-insert-section--parent nil)))) (progn nil (or (and (memq ... cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list ... section145))) (let* ((v section145)) (aset v 6 (let ... ...)))) (let ((magit-insert-section--current section145) (magit-insert-section--parent section145) (magit-insert-section--oldroot (or magit-insert-section--oldroot ...))) (catch (quote cancel-section) (message "DEBUG: Insert unfetched pull: %s" (eieio-oref stub ...)) (magit-insert heading) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section145) (set-marker-insertion-type (progn nil ... ...) t) (let* (... ... ...) (save-excursion ... ...)) (if (eq section145 magit-root-section) (magit-section-show section145) (progn nil ... ...))) section145)))))
  (while --dolist-tail-- (setq stub (car --dolist-tail--)) (let* ((id (eieio-oref stub (quote :number))) (req (eieio-oref (gh-pulls-get api user proj id) (quote :data))) (base-sha (eieio-oref (eieio-oref req (quote :base)) (quote :sha))) (base-ref (eieio-oref (eieio-oref req (quote :base)) (quote :ref))) (head-sha (eieio-oref (eieio-oref req (quote :head)) (quote :sha))) (invalid (equal (eieio-oref (eieio-oref req (quote :head)) (quote :ref)) head-sha)) (have-commits (and (eql 0 (magit-git-exit-code "cat-file" "-e" base-sha)) (eql 0 (magit-git-exit-code "cat-file" "-e" head-sha)))) (applied (and have-commits (magit-git-string "branch" branch (format "--contains=%s" head-sha)))) (heading (format "[%s@%s] %s\n" (propertize (number-to-string id) (quote face) (quote magit-tag)) (if (string= base-ref branch) (propertize base-ref (quote face) (quote magit-branch-local)) base-ref) (propertize (eieio-oref req (quote :title)) (quote face) (cond (applied ...) (have-commits nil) (invalid ...) (t ...))))) (info (list user proj id))) (message "DEBUG %s: have commits: %S" (eieio-oref stub (quote :title)) have-commits) (cond (have-commits (let* ((section143 (progn "Constructor for objects of type `magit-section'." nil ...))) (progn nil (or (and ...) (signal ... ...)) (let* (...) (aset v 6 ...))) (let ((magit-insert-section--current section143) (magit-insert-section--parent section143) (magit-insert-section--oldroot ...)) (catch (quote cancel-section) (magit-insert heading) (magit-insert-heading) (if ... ...) (run-hooks ...) (magit-insert-child-count section143) (set-marker-insertion-type ... t) (let* ... ...) (if ... ... ...)) section143))) (invalid (let* ((section144 (progn "Constructor for objects of type `magit-section'." nil ...))) (progn nil (or (and ...) (signal ... ...)) (let* (...) (aset v 6 ...))) (let ((magit-insert-section--current section144) (magit-insert-section--parent section144) (magit-insert-section--oldroot ...)) (catch (quote cancel-section) (magit-insert heading) (run-hooks ...) (magit-insert-child-count section144) (set-marker-insertion-type ... t) (let* ... ...) (if ... ... ...)) section144))) (t (let* ((section145 (progn "Constructor for objects of type `magit-section'." nil ...))) (progn nil (or (and ...) (signal ... ...)) (let* (...) (aset v 6 ...))) (let ((magit-insert-section--current section145) (magit-insert-section--parent section145) (magit-insert-section--oldroot ...)) (catch (quote cancel-section) (message "DEBUG: Insert unfetched pull: %s" ...) (magit-insert heading) (run-hooks ...) (magit-insert-child-count section145) (set-marker-insertion-type ... t) (let* ... ...) (if ... ... ...)) section145))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- stubs) stub) (while --dolist-tail-- (setq stub (car --dolist-tail--)) (let* ((id (eieio-oref stub (quote :number))) (req (eieio-oref (gh-pulls-get api user proj id) (quote :data))) (base-sha (eieio-oref (eieio-oref req (quote :base)) (quote :sha))) (base-ref (eieio-oref (eieio-oref req (quote :base)) (quote :ref))) (head-sha (eieio-oref (eieio-oref req (quote :head)) (quote :sha))) (invalid (equal (eieio-oref (eieio-oref req ...) (quote :ref)) head-sha)) (have-commits (and (eql 0 (magit-git-exit-code "cat-file" "-e" base-sha)) (eql 0 (magit-git-exit-code "cat-file" "-e" head-sha)))) (applied (and have-commits (magit-git-string "branch" branch (format "--contains=%s" head-sha)))) (heading (format "[%s@%s] %s\n" (propertize (number-to-string id) (quote face) (quote magit-tag)) (if (string= base-ref branch) (propertize base-ref ... ...) base-ref) (propertize (eieio-oref req ...) (quote face) (cond ... ... ... ...)))) (info (list user proj id))) (message "DEBUG %s: have commits: %S" (eieio-oref stub (quote :title)) have-commits) (cond (have-commits (let* ((section143 ...)) (progn nil (or ... ...) (let* ... ...)) (let (... ... ...) (catch ... ... ... ... ... ... ... ... ...) section143))) (invalid (let* ((section144 ...)) (progn nil (or ... ...) (let* ... ...)) (let (... ... ...) (catch ... ... ... ... ... ... ...) section144))) (t (let* ((section145 ...)) (progn nil (or ... ...) (let* ... ...)) (let (... ... ...) (catch ... ... ... ... ... ... ... ...) section145))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (catch (quote cancel-section) (magit-insert-heading "Pull Requests:") (let ((--dolist-tail-- stubs) stub) (while --dolist-tail-- (setq stub (car --dolist-tail--)) (let* ((id (eieio-oref stub (quote :number))) (req (eieio-oref (gh-pulls-get api user proj id) (quote :data))) (base-sha (eieio-oref (eieio-oref req ...) (quote :sha))) (base-ref (eieio-oref (eieio-oref req ...) (quote :ref))) (head-sha (eieio-oref (eieio-oref req ...) (quote :sha))) (invalid (equal (eieio-oref ... ...) head-sha)) (have-commits (and (eql 0 ...) (eql 0 ...))) (applied (and have-commits (magit-git-string "branch" branch ...))) (heading (format "[%s@%s] %s\n" (propertize ... ... ...) (if ... ... base-ref) (propertize ... ... ...))) (info (list user proj id))) (message "DEBUG %s: have commits: %S" (eieio-oref stub (quote :title)) have-commits) (cond (have-commits (let* (...) (progn nil ... ...) (let ... ... section143))) (invalid (let* (...) (progn nil ... ...) (let ... ... section144))) (t (let* (...) (progn nil ... ...) (let ... ... section145))))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if (not cached\?) (progn (insert "Press `# g` to update the pull request list.\n\n"))) (if (> (length stubs) 0) (progn (insert "\n"))) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section142) (set-marker-insertion-type (progn nil (or (and (memq (aref section142 0) cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list (quote magit-section) section142))) (aref section142 3)) t) (let* ((end (progn nil (or (and (memq ... cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list ... section142))) (let* ((v section142)) (aset v 5 (point-marker))))) (map (intern (format "magit-%s-section-map" (progn nil (or ... ...) (aref section142 1))))) (map (and (boundp map) (symbol-value map)))) (save-excursion (goto-char (progn nil (or (and (memq ... cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list ... section142))) (aref section142 3))) (while (< (point) end) (let ((next (or ... end))) (if (get-text-property (point) (quote magit-section)) nil (put-text-property (point) next (quote magit-section) section142) (if map (progn ...))) (goto-char next))))) (if (eq section142 magit-root-section) (magit-section-show section142) (progn nil (or (and (memq (aref (progn nil ... ...) 0) cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list (quote magit-section) (progn nil (or ... ...) (aref section142 12))))) (let* ((v (progn nil (or ... ...) (aref section142 12)))) (aset v 13 (nconc (progn nil (or ... ...) (aref ... 13)) (list section142)))))))
  (let ((magit-insert-section--current section142) (magit-insert-section--parent section142) (magit-insert-section--oldroot (or magit-insert-section--oldroot (if magit-insert-section--parent nil (prog1 magit-root-section (setq magit-root-section section142)))))) (catch (quote cancel-section) (magit-insert-heading "Pull Requests:") (let ((--dolist-tail-- stubs) stub) (while --dolist-tail-- (setq stub (car --dolist-tail--)) (let* ((id (eieio-oref stub ...)) (req (eieio-oref ... ...)) (base-sha (eieio-oref ... ...)) (base-ref (eieio-oref ... ...)) (head-sha (eieio-oref ... ...)) (invalid (equal ... head-sha)) (have-commits (and ... ...)) (applied (and have-commits ...)) (heading (format "[%s@%s] %s\n" ... ... ...)) (info (list user proj id))) (message "DEBUG %s: have commits: %S" (eieio-oref stub (quote :title)) have-commits) (cond (have-commits (let* ... ... ...)) (invalid (let* ... ... ...)) (t (let* ... ... ...)))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if (not cached\?) (progn (insert "Press `# g` to update the pull request list.\n\n"))) (if (> (length stubs) 0) (progn (insert "\n"))) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section142) (set-marker-insertion-type (progn nil (or (and (memq (aref section142 0) cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list (quote magit-section) section142))) (aref section142 3)) t) (let* ((end (progn nil (or (and ...) (signal ... ...)) (let* (...) (aset v 5 ...)))) (map (intern (format "magit-%s-section-map" (progn nil ... ...)))) (map (and (boundp map) (symbol-value map)))) (save-excursion (goto-char (progn nil (or (and ...) (signal ... ...)) (aref section142 3))) (while (< (point) end) (let ((next ...)) (if (get-text-property ... ...) nil (put-text-property ... next ... section142) (if map ...)) (goto-char next))))) (if (eq section142 magit-root-section) (magit-section-show section142) (progn nil (or (and (memq (aref ... 0) cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list (quote magit-section) (progn nil ... ...)))) (let* ((v (progn nil ... ...))) (aset v 13 (nconc (progn nil ... ...) (list section142))))))) section142)
  (let* ((section142 (progn "Constructor for objects of type `magit-section'." nil (vector (quote cl-struct-magit-section) (quote pulls) nil (point-marker) nil nil nil nil nil nil nil nil magit-insert-section--parent nil)))) (progn nil (or (and (memq (aref section142 0) cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list (quote magit-section) section142))) (let* ((v section142)) (aset v 6 (let ((value (run-hook-with-args-until-success ... section142))) (if value (eq value (quote hide)) (let (...) (if it ... nil))))))) (let ((magit-insert-section--current section142) (magit-insert-section--parent section142) (magit-insert-section--oldroot (or magit-insert-section--oldroot (if magit-insert-section--parent nil (prog1 magit-root-section (setq magit-root-section section142)))))) (catch (quote cancel-section) (magit-insert-heading "Pull Requests:") (let ((--dolist-tail-- stubs) stub) (while --dolist-tail-- (setq stub (car --dolist-tail--)) (let* ((id ...) (req ...) (base-sha ...) (base-ref ...) (head-sha ...) (invalid ...) (have-commits ...) (applied ...) (heading ...) (info ...)) (message "DEBUG %s: have commits: %S" (eieio-oref stub ...) have-commits) (cond (have-commits ...) (invalid ...) (t ...))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if (not cached\?) (progn (insert "Press `# g` to update the pull request list.\n\n"))) (if (> (length stubs) 0) (progn (insert "\n"))) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section142) (set-marker-insertion-type (progn nil (or (and (memq ... cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list ... section142))) (aref section142 3)) t) (let* ((end (progn nil (or ... ...) (let* ... ...))) (map (intern (format "magit-%s-section-map" ...))) (map (and (boundp map) (symbol-value map)))) (save-excursion (goto-char (progn nil (or ... ...) (aref section142 3))) (while (< (point) end) (let (...) (if ... nil ... ...) (goto-char next))))) (if (eq section142 magit-root-section) (magit-section-show section142) (progn nil (or (and (memq ... cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list ... ...))) (let* ((v ...)) (aset v 13 (nconc ... ...)))))) section142))
  (progn (let* ((section142 (progn "Constructor for objects of type `magit-section'." nil (vector (quote cl-struct-magit-section) (quote pulls) nil (point-marker) nil nil nil nil nil nil nil nil magit-insert-section--parent nil)))) (progn nil (or (and (memq (aref section142 0) cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list (quote magit-section) section142))) (let* ((v section142)) (aset v 6 (let ((value ...)) (if value (eq value ...) (let ... ...)))))) (let ((magit-insert-section--current section142) (magit-insert-section--parent section142) (magit-insert-section--oldroot (or magit-insert-section--oldroot (if magit-insert-section--parent nil (prog1 magit-root-section ...))))) (catch (quote cancel-section) (magit-insert-heading "Pull Requests:") (let ((--dolist-tail-- stubs) stub) (while --dolist-tail-- (setq stub (car --dolist-tail--)) (let* (... ... ... ... ... ... ... ... ... ...) (message "DEBUG %s: have commits: %S" ... have-commits) (cond ... ... ...)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if (not cached\?) (progn (insert "Press `# g` to update the pull request list.\n\n"))) (if (> (length stubs) 0) (progn (insert "\n"))) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section142) (set-marker-insertion-type (progn nil (or (and ...) (signal ... ...)) (aref section142 3)) t) (let* ((end (progn nil ... ...)) (map (intern ...)) (map (and ... ...))) (save-excursion (goto-char (progn nil ... ...)) (while (< ... end) (let ... ... ...)))) (if (eq section142 magit-root-section) (magit-section-show section142) (progn nil (or (and ...) (signal ... ...)) (let* (...) (aset v 13 ...))))) section142)))
  (if (or (> (length stubs) 0) (not cached\?)) (progn (let* ((section142 (progn "Constructor for objects of type `magit-section'." nil (vector (quote cl-struct-magit-section) (quote pulls) nil (point-marker) nil nil nil nil nil nil nil nil magit-insert-section--parent nil)))) (progn nil (or (and (memq (aref section142 0) cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list (quote magit-section) section142))) (let* ((v section142)) (aset v 6 (let (...) (if value ... ...))))) (let ((magit-insert-section--current section142) (magit-insert-section--parent section142) (magit-insert-section--oldroot (or magit-insert-section--oldroot (if magit-insert-section--parent nil ...)))) (catch (quote cancel-section) (magit-insert-heading "Pull Requests:") (let ((--dolist-tail-- stubs) stub) (while --dolist-tail-- (setq stub ...) (let* ... ... ...) (setq --dolist-tail-- ...))) (if (not cached\?) (progn (insert "Press `# g` to update the pull request list.\n\n"))) (if (> (length stubs) 0) (progn (insert "\n"))) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section142) (set-marker-insertion-type (progn nil (or ... ...) (aref section142 3)) t) (let* ((end ...) (map ...) (map ...)) (save-excursion (goto-char ...) (while ... ...))) (if (eq section142 magit-root-section) (magit-section-show section142) (progn nil (or ... ...) (let* ... ...)))) section142))))
  (let* ((api (magit-gh-pulls-get-api)) (user (car repo)) (proj (cdr repo)) (cached\? (magit-gh-pulls-requests-cached-p api user proj)) (stubs (if cached\? (progn (funcall magit-gh-pulls-maybe-filter-pulls (eieio-oref (gh-pulls-list api user proj) (quote :data)))))) (branch (magit-get-current-branch))) (if (or (> (length stubs) 0) (not cached\?)) (progn (let* ((section142 (progn "Constructor for objects of type `magit-section'." nil (vector ... ... nil ... nil nil nil nil nil nil nil nil magit-insert-section--parent nil)))) (progn nil (or (and (memq ... cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list ... section142))) (let* ((v section142)) (aset v 6 (let ... ...)))) (let ((magit-insert-section--current section142) (magit-insert-section--parent section142) (magit-insert-section--oldroot (or magit-insert-section--oldroot ...))) (catch (quote cancel-section) (magit-insert-heading "Pull Requests:") (let (... stub) (while --dolist-tail-- ... ... ...)) (if (not cached\?) (progn ...)) (if (> ... 0) (progn ...)) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section142) (set-marker-insertion-type (progn nil ... ...) t) (let* (... ... ...) (save-excursion ... ...)) (if (eq section142 magit-root-section) (magit-section-show section142) (progn nil ... ...))) section142)))))
  (progn (let* ((api (magit-gh-pulls-get-api)) (user (car repo)) (proj (cdr repo)) (cached\? (magit-gh-pulls-requests-cached-p api user proj)) (stubs (if cached\? (progn (funcall magit-gh-pulls-maybe-filter-pulls (eieio-oref ... ...))))) (branch (magit-get-current-branch))) (if (or (> (length stubs) 0) (not cached\?)) (progn (let* ((section142 (progn "Constructor for objects of type `magit-section'." nil ...))) (progn nil (or (and ...) (signal ... ...)) (let* (...) (aset v 6 ...))) (let ((magit-insert-section--current section142) (magit-insert-section--parent section142) (magit-insert-section--oldroot ...)) (catch (quote cancel-section) (magit-insert-heading "Pull Requests:") (let ... ...) (if ... ...) (if ... ...) (run-hooks ...) (magit-insert-child-count section142) (set-marker-insertion-type ... t) (let* ... ...) (if ... ... ...)) section142))))))
  (if repo (progn (let* ((api (magit-gh-pulls-get-api)) (user (car repo)) (proj (cdr repo)) (cached\? (magit-gh-pulls-requests-cached-p api user proj)) (stubs (if cached\? (progn (funcall magit-gh-pulls-maybe-filter-pulls ...)))) (branch (magit-get-current-branch))) (if (or (> (length stubs) 0) (not cached\?)) (progn (let* ((section142 ...)) (progn nil (or ... ...) (let* ... ...)) (let (... ... ...) (catch ... ... ... ... ... ... ... ... ... ...) section142)))))))
  (let* ((repo (magit-gh-pulls-guess-repo))) (if repo (progn (let* ((api (magit-gh-pulls-get-api)) (user (car repo)) (proj (cdr repo)) (cached\? (magit-gh-pulls-requests-cached-p api user proj)) (stubs (if cached\? (progn ...))) (branch (magit-get-current-branch))) (if (or (> (length stubs) 0) (not cached\?)) (progn (let* (...) (progn nil ... ...) (let ... ... section142))))))))
  (progn (let* ((repo (magit-gh-pulls-guess-repo))) (if repo (progn (let* ((api (magit-gh-pulls-get-api)) (user (car repo)) (proj (cdr repo)) (cached\? (magit-gh-pulls-requests-cached-p api user proj)) (stubs (if cached\? ...)) (branch (magit-get-current-branch))) (if (or (> ... 0) (not cached\?)) (progn (let* ... ... ...))))))))
  (condition-case print-section (progn (let* ((repo (magit-gh-pulls-guess-repo))) (if repo (progn (let* ((api ...) (user ...) (proj ...) (cached\? ...) (stubs ...) (branch ...)) (if (or ... ...) (progn ...))))))) ((debug error) nil))
  magit-gh-pulls-insert-gh-pulls()
  run-hooks(magit-status-sections-hook)
  magit-status-refresh-buffer()
  apply(magit-status-refresh-buffer nil)
  magit-refresh-buffer()
  magit-refresh()
  magit-gh-pulls-reload()
  funcall-interactively(magit-gh-pulls-reload)
  call-interactively(magit-gh-pulls-reload)
  magit-invoke-popup-action(114)
  funcall-interactively(magit-invoke-popup-action 114)
  call-interactively(magit-invoke-popup-action nil nil)
  command-execute(magit-invoke-popup-action)
```

**Comment by sigma** [comment] 2015-11-18 16:12
fixed now

**Closed by sigma** 2015-11-18 16:12 UTC

**Comment by syl20bnr** [comment] 2015-11-19 04:20
Thank you @lunaryorn for the stack and @sigma for the fix, I can confirm that it works well now :100:
