### ISSUE TITLE
Creating a PR without pushing the branch should ask me if I want to push the branch first.

### ISSUE THREAD

**Issue by adamdecaf** [sigma/magit-gh-pulls#39] opened 2015-08-10 15:46 UTC
I'm liking magit-gh-pulls so far! However, I noticed that when I was creating a PR I forgot to push my branch first.. Which meant I had to see the error, push the branch and then work through the `# g c` steps again. It would be nice to ask me (or re-do the PR creation).

**Comment by alexander-yakushev** [comment] 2015-08-10 15:48
Good point, I will take a look.

**Comment by stig** [comment] 2015-08-11 13:09
I'd love this.

**Comment by alexander-yakushev** [comment] 2015-10-19 13:59
@adamdecaf @stig With the latest version I've just pushed, magit-gh-pulls will try to figure out that PR branch was not pushed and will propose to push it. I will appreciate if you test this new behavior.

**Comment by stig** [comment] 2015-10-19 14:00
Would be delighted to. Will it arrive on melpa soon, or should I install from git for this testing?

**Comment by alexander-yakushev** [comment] 2015-10-19 14:01
I think melpa will pick it up in less than an hour.

**Comment by stig** [comment] 2015-10-19 16:46
_3 hours later_: Not on melpa yet, it seems :-(
If it doesn't end up on melpa by tomorrow morning I'll install directly from git to test.

**Comment by alexander-yakushev** [comment] 2015-10-19 19:09
@stig Looks like it's there already.

**Comment by stig** [comment] 2015-10-19 20:22
Oh, so it is now. I am loving the new magit-popup interface, but it seems that it does not ask me to push the branch. Also, it apparently no longer opens the PR on github automatically. (I enjoyed this because unless I tag the PR with "ready for review" it will not be reviewed by my colleagues.)

**Comment by alexander-yakushev** [comment] 2015-10-19 20:34
There is now a customizable option `-w` that can be enabled from the popup. You can change it every time you create a PR, or just set it once and do `C-x C-s`.

It's strange that it doesn't ask you to push the branch. Have you tried it on a branch that you added some commits to, then you create a PR, it doesn't ask anything and fails with an error?

**Comment by stig** [comment] 2015-10-19 20:45
Oh, thanks for the `-w` option, that's great! Sorry I didn't notice.

I just tried again to create a PR. These are the steps:

1. I created a fresh branch
2. I made a commit
3. I used `# c` to create a PR

It then failed with this error:
<img width="700" alt="magit gh pulls error" src="https://cloud.githubusercontent.com/assets/45407/10590810/a8f67678-76aa-11e5-94b1-3c7725092117.png">

**Comment by alexander-yakushev** [comment] 2015-10-19 20:47
OK, so the code for checking if the branch is pushed is quite unreliable, honestly. I will try to do something about it tomorrow. Thanks for testing!

**Comment by alexander-yakushev** [comment] 2015-10-20 11:48
@stig I've pushed a fix that might resolve some of the issues. Still, creating PRs works only if you create them from a branch in the same repository. It doesn't work from a fork, and I'm not sure if it worked like that before. Could you please clarify that, and also check if the latest version fixes the 422 error? Thanks!

You might want to skip waiting for MELPA and just `load-file` the file pasted from github.

**Comment by stig** [comment] 2015-10-20 11:52
That PR creation only works for the same repo is fine for me. That is my main use case. It's comparatively rare that I do PRs against other people's repos. Will try to check now.

**Comment by stig** [comment] 2015-10-20 12:06
I can confirm that creating a new branch, adding a commit, then creating a PR prompts me to push the branch and creating the PR works successfully :-)

**Comment by alexander-yakushev** [comment] 2015-10-20 12:14
Great! There is one hidden issue though — the plugin doesn't wait for `git push` to finish, so potentially it is possible for the error to occur if the pushed commits are big and you fill in Title and Description too quickly. But I don't think it will happen often.

So I guess I can close this now. Thanks for help, Stig!

**Closed by alexander-yakushev** 2015-10-20 12:14 UTC
Labels: enhancement

**Comment by stig** [comment] 2015-10-20 12:52
As long as at least 1 commit is pushed the PR should succeed. If there are a lot of commits they don't all have to be pushed.

**Comment by alexander-yakushev** [comment] 2015-10-20 13:09
I'm not sure about that. git updates remote refs only after all data came through. Github won't know that a few commits were pushed to the branch until all of them are there.

**Comment by stig** [comment] 2015-10-20 13:13
Ooh, you might be right there. sorry, my bad.

**Comment by adamdecaf** [comment] 2015-10-20 13:17
Thanks @alexander-yakushev !
